name: 'Terraform'
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check -recursive -no-color

      - name: Run Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          framework: terraform
          directory: .
          output_format: github_failed_only
          quiet: true
          soft_fail: true

      - name: Checkov Report
        id: checkov-report
        working-directory: .
        run: |
          while IFS= read -r line; do
            echo "$line" >> $GITHUB_STEP_SUMMARY
          done < results_github_failed_only.md

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@main
        with:
          working-dir: ./azure-*/
          output-file: README.md
          output-method: inject
          git-push: true
